| Data name| In master function |  All years variable
| -------- | -------- |  -------- | 
|Schüler/-innen je Lehrkraft | teachers| teachers_concat
|Anzahl an Lehrkräften | students_per_teacher| students_per_teacher_concat
|Anzahl an Schülern | students| students_concat
|Unterichtsstd. Je Schüler	| hours_per_student|hours_per_student_concat

In [1]:
import pandas as pd
#pd.set_option('display.max_rows', None)

from master import hours_per_student_concat

In [2]:
hours_per_student_concat.head()

,SchoolType,Baden-Wüttemberg,Bayern,Berlin,Brandenburg,Bremen,Hamburg,Hessen,Mecklenburg-Vorpommern,Niedersachsen,Nordrhein-Westfalen,Rheinland-Pfalz,Saarland,Sachsen,Sachsen-Anhalt,Schleswig-Holstein,Thüringen,Deutschland,Year
0,Allgemein bildende Schulen,1.713945,1.585794,1.754554,1.770079,1.714481,1.690766,1.648265,1.788607,1.566029,1.523436,1.617019,1.699214,1.782667,1.856108,1.524647,1.830527,1.626870,2011
1,Förderschulen,5.322422,3.174173,3.976845,4.241515,4.702265,3.895806,4.469091,3.223718,3.733670,4.037930,4.060919,4.326110,3.722410,3.548922,4.031242,3.720916,4.039715,2011
2,Sekundarbereich I,1.573263,1.560799,1.795453,1.787801,1.664775,1.611509,1.533235,1.830719,1.482593,1.438379,1.466960,1.545581,1.751113,1.772398,1.472075,1.822960,1.549745,2011
3,Sekundarbereich II,1.315289,1.137183,1.326992,1.277223,1.114163,1.192419,1.171841,1.179430,1.151818,1.112564,1.164155,1.131329,1.414989,1.175738,1.095811,1.395624,1.189990,2011
4,Allgemein bildende Schulen,1.725627,1.603869,1.755236,1.763702,1.721590,1.720837,1.668937,1.785292,1.601169,1.549926,1.652337,1.688443,1.785647,1.862386,1.530059,1.804278,1.645586,2012